server:
  port: ${CUSTOM.SERVER.PORT:9005}

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ce80dd6b15ef286a1413
            client-secret: cf677985f9032e2133ae17213d52ade3880235f7